
# Setup
title:        kdavis91.github.io
tagline:      Data Science and Physics problems on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"
share: true

# About/contact
author:
  name:       Kyle Davis
  avatar:     "/avatar.jpg"
  location:   "Somwhere, UK"
  url:        kdavis91.github.io
  github:     "https://github.com/kdavis91"
  keybase:    "tensorinsights*keybase.io"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
