
# Setup
title:        kdavis91.github.io
tagline:      Data Science and Physics problems on GitHub Pages
baseurl:      "https://pietromenna.github.io/jekyll-cayman-theme"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Kyle Davis
  url:        kdavis91.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
